apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    jupyter: jupyter
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        jupyter: jupyter
        octopusexport: OctopusExport
    spec:
      hostNetwork: false
      containers:
        - name: jupyter
          image: 'jupyter/scipy-notebook:abdb27a6dfbb'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
